---
- name: create certificates directory
  file: 
    dest: /usr/local/share/ca-certificates
    owner: root
    group: root
    state: directory

- name: Copy the crt file
  copy: 
    src: domain.crt
    dest: "/etc/pki/ca-trust/source/anchors/docker-registry.crt"

- name: Insert the hostname
  lineinfile: dest=/etc/hosts line="{{ registry_ip }} {{ registry_domain }}"

- name: update certification
  shell: "update-ca-trust"
  handlers: restart docker

